name: HomeTown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#a6a8a5'
    - '#d99a00'
    - '#354a00'
  brandStrength: 0.8125
  lightness: 0.542921383632347
  saturation: 0.7966945478692651
  rhythmicContrast: 0.10235616588033736
purpose: []
