name: HomeTown
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b86a3'
    - '#fcfaee'
    - '#000000'
    - '#e1a46d'
    - '#787a10'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
